task:
  name: Build and Test
  container:
    image: rust:slim-bookworm

  build_script:
    - cargo build --release

  test_script:
    - cargo test

  check_format_for_script:
    - cargo fmt --check