task:
  name: Build and Test
  container:
    image: rust:slim-bookworm

  setup_script:
    - apt-get update -y
    - apt-get install -y --fix-missing build-essential

  build_script:
    - cargo build --release

  test_script:
    - cargo test --release

  check_format_script:
    - rustup component add rustfmt
    - cargo fmt --check